name: Hourly Lottery History Update

# Explicitly give the workflow write access to repo contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (all branches + credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Show current Git remotes & branches
        run: |
          echo "--- local branches ---"
          git branch -vv
          echo
          echo "--- remote info ---"
          git remote -v
          echo
          echo "--- HEAD ---"
          git rev-parse --abbrev-ref HEAD

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update_jackpots.py
        run: |
          python update_jackpots.py

      - name: Commit & push history.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Checking for changes to history.json..."
          if [ -n "$(git status --porcelain history.json)" ]; then
            echo "⚡ history.json has changed. Preparing to commit and push..."
            git add history.json
            git commit -m "Update lottery history $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

            echo "> Before push, show remotes and HEAD:"
            git branch -vv
            git remote -v

            git push origin HEAD:gh-pages
            echo "✅ Pushed history.json to gh-pages."
          else
            echo "ℹ️ No changes in history.json; skipping commit."
          fi
